ALTER TABLE "User"
ADD COLUMN "quietHoursEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "quietHoursStartMinutes" INTEGER NOT NULL DEFAULT 1320,
ADD COLUMN "quietHoursEndMinutes" INTEGER NOT NULL DEFAULT 480,
ADD COLUMN "quietHoursTimeZone" TEXT NOT NULL DEFAULT 'UTC';

ALTER TABLE "ConversationMember"
ADD COLUMN "pushMuted" BOOLEAN NOT NULL DEFAULT false;
